language: c
group: travis_latest

git:
  depth: 25
  quiet: true

env: FC=gfortran

addons:
  apt:
#    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran


install:
- cd build
- cmake ..
- cmake --build .

script: ctest --output-on-failure
