name: ci_linux

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**.txt"
      - ".github/workflows/ci_linux.yml"
  pull_request:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**.txt"
      - ".github/workflows/ci_linux.yml"

jobs:

  linuxCMake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: install prereqs
      run: |
        pip install cmake
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran

    - run: cmake -B build
      env:
        FC: gfortran
        CC: gcc
        CXX: g++
    - run: cmake --build build --parallel
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Cmake_Buildlog
        path: build/CMakeFiles/CMakeError.log

    - run: ctest -V
      working-directory: build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_CMake_Testlog
        path: build/Testing/Temporary/LastTest.log
